projects:
  amplifyDatasource:
    schemaPath: amplify/backend/api/amplifyDatasource/build/schema.graphql
    includes:
      - exit
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
extensions:
  amplify:
    version: 3
